### ISSUE TITLE
Install failure on Mac OSX using only .Net Core

### ISSUE THREAD

**Issue by SeanSnyders** [tjanczuk/edge#529]
Trying to install Edge on OSX `10.11.3` using just .Net Core `1.0.0-preview2-1-003177` and **no Mono** installed.
Seems the configure of Edge still requires Mono to be installed? I've tried setting `EDGE_USE_CORECLR=1` as well before running the install, but no luck. I followed the installation documentation and it states that Mono is not needed.

Using Node `6.10.0`, npm `4.4.1`.

Getting this failure during `npm install edge`:
```
> edge@6.5.1 install /<project path>/node_modules/edge
> node tools/install.js

Package mono-2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `mono-2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'mono-2' found
gyp: Call to 'pkg-config mono-2 --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:308:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /<project path>/node_modules/edge
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
```

If I just continue and try to run my app that uses .Net Core, I get this error:
```
$ npm start

> <project>@0.1.0 start /<project path>
> electron ./app

App threw an error during load
Error: The edge native module is not available at /<project path>/app/node_modules/electron-edge/build/Release/edge_coreclr.node.
You can use EDGE_NATIVE environment variable to provide alternate location of edge.node. If you need to build edge.node, follow build instructions for your platform at https://github.com/tjanczuk/edge
    at Object.<anonymous> (/<project path>/app/node_modules/electron-edge/lib/edge.js:32:11)
    at Object.<anonymous> (/<project path>/app/node_modules/electron-edge/lib/edge.js:171:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/<project path>/app/main.js:1:167)

```

**Comment by srivollier** [comment]
Hey !  Try that : PKG_CONFIG_PATH=/Library/Frameworks/Mono.framework/Versions/Current/lib/pkgconfig npm install edge.
But after, I get an other problem [glib.h file not found](https://github.com/tjanczuk/edge/issues/527)
Hope this will help

**Comment by SeanSnyders** [comment]
Thanks @srivollier, I tried that and go this error due to not having Mono installed:
```
$ PKG_CONFIG_PATH=/Library/Frameworks/Mono.framework/Versions/Current/lib/pkgconfig npm install edge

> edge@6.5.1 install /<project path>/node_modules/edge
> node tools/install.js

  CXX(target) Release/obj.target/edge_nativeclr/src/mono/clractioncontext.o
In file included from ../src/mono/clractioncontext.cpp:1:
In file included from ../src/mono/edge.h:7:
In file included from /Library/Frameworks/Mono.framework/Versions/Current/include/mono-2.0/mono/metadata/class.h:6:
/Library/Frameworks/Mono.framework/Versions/Current/include/mono-2.0/mono/metadata/loader.h:7:10: fatal error: 
      'mono/utils/mono-dl.h' file not found
#include <mono/utils/mono-dl.h>
         ^
1 error generated.
```

**Comment by sla89** [comment]
Same issue here but on Ubuntu 16.04.

**Comment by akunkle** [comment]
This is caused by a change in Mono 4.8.  I downgraded to 4.6 and the problem went away.  The build scripts need to be changed before edge will work on 4.8.

**Comment by SeanSnyders** [comment]
@akunkle, So the problem is due to changes in the build script that was introduced with Edge supporting Mono 4.8?
You mention you downgraded to 4.6 and the problem went away. The issue I am having is due to having **no** Mono installed, so there is nothing to downgrade on my part....

Should I try and use a different version of Edge pre supporting Mono 4.8?

**Comment by SeanSnyders** [comment]
@sla89 so you are having the same issue trying to install Edge **without Mono** on Linux and having the same problems...? If so, I can change the title of this issue to not be macOS specific.

**Comment by sla89** [comment]
@SeanSnyders yes - thats the case.

**Comment by SeanSnyders** [comment]
@tjanczuk Any input here?

**Comment by SeanSnyders** [comment]
It seems that edge will always need Mono installed as it includes native header files from Mono in the non-windows build of edge:
![image](https://cloud.githubusercontent.com/assets/1384135/24688533/a971b162-1a14-11e7-825f-5f0465d49407.png)

@tjanczuk is this correct? If so, the documentation should be updated to reflect this.

**Comment by NandoMB** [comment]
Still not workin :(
