### ISSUE TITLE
Building with node-webkit

### ISSUE THREAD

**Issue by mikeptweet** [tjanczuk/edge#5]
First of all, this is awesome ... thanks for putting this together.

I am trying to build the module to use in node-webkit, following the instructions here

https://github.com/rogerwang/nw-gyp

I get the following errors ...

C:\owin-master>nw-gyp build
gyp info it worked if it ends with ok
gyp info using nw-gyp@0.7.3-4
gyp info using node@0.8.21 | win32 | x64
gyp info spawn msbuild
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=Win32' ]
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  utils.cpp
  clrfuncinvokecontext.cpp
  nodejsfunc.cpp
  owinjavascriptconverter.cpp
c:\owin-master\src\owin.h(135): error C2217: 'override' requires 'virtual' [C:\
owin-master\build\owin.vcxproj]
c:\owin-master\src\owin.h(135): error C2217: 'override' requires 'virtual' [C:\
owin-master\build\owin.vcxproj]
c:\owin-master\src\owin.h(135): error C2217: 'override' requires 'virtual' [C:\
owin-master\build\owin.vcxproj]
c:\owin-master\src\owin.h(143): error C2217: 'override' requires 'virtual' [C:\
owin-master\build\owin.vcxproj]
c:\owin-master\src\owin.h(143): error C2217: 'override' requires 'virtual' [C:\
owin-master\build\owin.vcxproj]
c:\owin-master\src\owin.h(143): error C2217: 'override' requires 'virtual' [C:\
owin-master\build\owin.vcxproj]
c:\owin-master\src\owin.h(135): error C2217: 'override' requires 'virtual' [C:\
owin-master\build\owin.vcxproj]
c:\owin-master\src\owin.h(147): error C2217: 'override' requires 'virtual' [C:\
owin-master\build\owin.vcxproj]
c:\owin-master\src\owin.h(147): error C2217: 'override' requires 'virtual' [C:\
owin-master\build\owin.vcxproj]
c:\owin-master\src\owin.h(147): error C2217: 'override' requires 'virtual' [C:\
owin-master\build\owin.vcxproj]
c:\owin-master\src\owin.h(143): error C2217: 'override' requires 'virtual' [C:\
owin-master\build\owin.vcxproj]
c:\owin-master\src\owin.h(147): error C2217: 'override' requires 'virtual' [C:\
owin-master\build\owin.vcxproj]
  nodejsfuncinvokecontext.cpp
  clrfunc.cpp
  owin.cpp
c:\owin-master\src\owin.h(135): error C2217: 'override' requires 'virtual' [C:\
owin-master\build\owin.vcxproj]
c:\owin-master\src\owin.h(143): error C2217: 'override' requires 'virtual' [C:\
owin-master\build\owin.vcxproj]
c:\owin-master\src\owin.h(147): error C2217: 'override' requires 'virtual' [C:\
owin-master\build\owin.vcxproj]
c:\owin-master\src\owin.h(135): error C2217: 'override' requires 'virtual' [C:\
owin-master\build\owin.vcxproj]
c:\owin-master\src\owin.h(143): error C2217: 'override' requires 'virtual' [C:\
owin-master\build\owin.vcxproj]
c:\owin-master\src\owin.h(147): error C2217: 'override' requires 'virtual' [C:\
owin-master\build\owin.vcxproj]
c:\owin-master\src\owin.h(135): error C2217: 'override' requires 'virtual' [C:\
owin-master\build\owin.vcxproj]
c:\owin-master\src\owin.h(143): error C2217: 'override' requires 'virtual' [C:\
owin-master\build\owin.vcxproj]
c:\owin-master\src\owin.h(147): error C2217: 'override' requires 'virtual' [C:\
owin-master\build\owin.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\mparsons\AppData\Roaming\npm
\node_modules\nw-gyp\lib\build.js:232:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:99:17)
gyp ERR! stack     at Process._handle.onexit (child_process.js:678:10)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Users\mparsons\AppData\Roaming\npm\node_module
s\nw-gyp\bin\nw-gyp.js" "build"
gyp ERR! cwd C:\owin-master
gyp ERR! node -v v0.8.21
gyp ERR! nw-gyp -v v0.7.3-4
gyp ERR! not ok

Any chance you could have a look at this?

**Comment by frankhale** [comment]
The latest version of Edge compiles nicely against Node 0.12.x. I just got Edge working with Node-Webkit 0.12 and you can see an example here:

https://github.com/frankhale/nw-edge-example
